version: "3"

services:
    nginx:
        build: .
        container_name: nginx_node
        environment:
            CERTBOT_EMAIL: EMAIL # Required

            # https://github.com/JonasAlfredsson/docker-nginx-certbot#optional
            STAGING: 0
            RENEWAL_INTERVAL: 8d
            DEBUG: 0
        ports:
            - 80:80
            - 443:443
        volumes:
            #  Optional

            # - ./logs:/var/log/nginx
            # - ./nginx_config_files:/etc/nginx/user_conf.d

            - ./custom:/app/custom # Not needed when not using any custom files, this is used as a cache.

            # Required

            - ./letsencrypt:/etc/letsencrypt
            - ./config:/app/config
