version: "3"

services:
    nginx:
        build: .
        container_name: nginx_node
        environment:
            CERTBOT_EMAIL: certbot@samtaen.nl
            STAGING: 1
            RENEWAL_INTERVAL: 8d
            DEBUG: 1
            TZ: Europe/Amsterdam
