version: "3"

services:
    nginx:
        build: .
        container_name: nginx_node
        environment:
            CERTBOT_EMAIL: EMAIL # Required

            # https://github.com/JonasAlfredsson/docker-nginx-certbot#optional
            STAGING: 0
            RENEWAL_INTERVAL: 8d
            DEBUG: 0
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./letsencrypt:/etc/letsencrypt
            - ./logs:/var/log/nginx
            - ./config:/app/config
