version: "3.3"

services:
    nginx:
        image: netfloex/nginx:v.1.0.3
        container_name: nginx_config_manager
        environment:
            CERTBOT_EMAIL: EMAIL # Required

            # https://github.com/JonasAlfredsson/docker-nginx-certbot#optional
            STAGING: 0
            RENEWAL_INTERVAL: 8d
            DEBUG: 0
        ports:
            - 80:80
            - 443:443
        volumes:
            #  Optional

            # - ./logs:/var/log/nginx
            # - ./nginx_config_files:/etc/nginx/user_conf.d
            - ./data:/app/data # Needed when using custom files or cloudflare, this is used as a cache.

            # Required

            - ./letsencrypt:/etc/letsencrypt
            - ./config:/app/config
