name: docker-build

on:
    push:
        branches:
            - master

jobs:
    typescript:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup NodeJS v12
              uses: actions/setup-node@v2
              with:
                  node-version: 12
                  # cache: yarn
            - run: npm i yarn -g

            - name: Install Dependencies
              run: yarn install
            - name: Run tests
              run: yarn test
            - name: Test ESLint
              run: yarn lint

            - name: Build
              run: yarn build
            - name: Create Nginx Config folder
              run: mkdir nginx_config_files
            - name: Run
              run: yarn start
              env:
                  DONT_DOWNLOAD_FILES: true
                  DONT_CHECK_HOSTS: true
                  CONFIG_FILE: src/tests/configs/full-valid-config.json

    docker:
        runs-on: ubuntu-latest
        needs: typescript
        steps:
            # Setup
            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1
            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            # Login
            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: netfloex
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            # Build & Push
            - name: Build Dockerfile and push
              uses: docker/build-push-action@v2
              with:
                  push: true
                  tags: netfloex/nginx:latest
                  platforms: |
                      linux/amd64
                      linux/arm64
                      linux/arm/v7

                  # Cache
                  cache-from: type=gha
                  cache-to: type=gha
