name: docker-build

on:
    push:
        branches:
            - master

jobs:
    typescript:
        runs-on: ubuntu-latest
        steps:
            - name: Setup yarn and install dependencies
              uses: netfloex/actions/yarn@master

            - name: Run tests
              run: yarn test
            - name: Test ESLint
              run: yarn lint

            - name: Build
              run: yarn build
            - name: Create Nginx Config folder
              run: mkdir nginx/conf.d -p
            - name: Remove non production dependencies
              run: yarn install --production
            - name: Run
              run: yarn start
              env:
                  DONT_DOWNLOAD_FILES: true
                  DONT_CHECK_HOSTS: true
                  CERTBOT_EMAIL: required
                  CONFIG_FILE: src/tests/configs/full-valid-config.json

    withnginx:
        runs-on: ubuntu-latest
        needs: typescript
        steps:
            - name: Build and push to docker hub
              uses: netfloex/actions/docker@master
              with:
                  username: netfloex
                  token: ${{ secrets.DOCKERHUB_TOKEN }}
                  tags: netfloex/nginx:latest

    standalone:
        runs-on: ubuntu-latest
        needs: typescript
        steps:
            - name: Build and push to docker hub
              uses: netfloex/actions/docker@master
              with:
                  username: netfloex
                  token: ${{ secrets.DOCKERHUB_TOKEN }}
                  file: ./Dockerfile.standalone
                  tags: netfloex/nginx:standalone
