name: docker-build-versioned

on:
    push:
        tags:
            - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
    latest:
        runs-on: ubuntu-latest
        steps:
            - name: Get latest tag
              id: vars
              run: echo ::set-output name=tag::${GITHUB_REF:10}

            - name: Build and push to docker hub
              uses: netfloex/actions/docker@master
              with:
                  username: netfloex
                  token: ${{ secrets.DOCKERHUB_TOKEN }}
                  tags: netfloex/nginx:${{ steps.vars.outputs.tag }}

    standalone:
        runs-on: ubuntu-latest
        steps:
            - name: Get latest tag
              id: vars
              run: echo ::set-output name=tag::${GITHUB_REF:10}

            - name: Build and push to docker hub
              uses: netfloex/actions/docker@master
              with:
                  username: netfloex
                  token: ${{ secrets.DOCKERHUB_TOKEN }}
                  file: ./Dockerfile.standalone
                  tags: netfloex/nginx:standalone-${{ steps.vars.outputs.tag }}
